require('talhaimran.lazy')
require('talhaimran.options')
require('talhaimran.treesitter')
require('talhaimran.keymaps')
require('talhaimran.comments')
require('talhaimran.harpoon')
require('talhaimran.nvim-tmux-navigator')
